//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace globalization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Controls {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Controls() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("controls.sl.globalization.Controls", typeof(Controls).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this MsgBox already has a Control.
        /// </summary>
        public static string sErrorMsgBox1 {
            get {
                return ResourceManager.GetString("sErrorMsgBox1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to left panel.
        /// </summary>
        public static string sNoticeHaulierControl1 {
            get {
                return ResourceManager.GetString("sNoticeHaulierControl1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to right panel.
        /// </summary>
        public static string sNoticeHaulierControl2 {
            get {
                return ResourceManager.GetString("sNoticeHaulierControl2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set new timings values or attach another file. \nButton &apos;ALL&apos; will update all assets containing the original file.
        /// </summary>
        public static string sNoticeMsgBox1 {
            get {
                return ResourceManager.GetString("sNoticeMsgBox1", resourceCulture);
            }
        }
    }
}
