//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace globalization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("globalization.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string sAdd {
            get {
                return ResourceManager.GetString("sAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional information.
        /// </summary>
        public static string sAdditionalInformation {
            get {
                return ResourceManager.GetString("sAdditionalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        public static string sAdvanced {
            get {
                return ResourceManager.GetString("sAdvanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string sAll {
            get {
                return ResourceManager.GetString("sAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And.
        /// </summary>
        public static string sAnd {
            get {
                return ResourceManager.GetString("sAnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string sApply {
            get {
                return ResourceManager.GetString("sApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ARE YOU SURE???.
        /// </summary>
        public static string sAreYouSureStrong {
            get {
                return ResourceManager.GetString("sAreYouSureStrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention.
        /// </summary>
        public static string sAttention {
            get {
                return ResourceManager.GetString("sAttention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization.
        /// </summary>
        public static string sAuthorization {
            get {
                return ResourceManager.GetString("sAuthorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Availiable.
        /// </summary>
        public static string sAvailiable {
            get {
                return ResourceManager.GetString("sAvailiable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string sBack {
            get {
                return ResourceManager.GetString("sBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to between.
        /// </summary>
        public static string sBetween {
            get {
                return ResourceManager.GetString("sBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string sBrowse {
            get {
                return ResourceManager.GetString("sBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string sCancel {
            get {
                return ResourceManager.GetString("sCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled.
        /// </summary>
        public static string sCanceled {
            get {
                return ResourceManager.GetString("sCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to changes have been saved.
        /// </summary>
        public static string sChangesSaved {
            get {
                return ResourceManager.GetString("sChangesSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains.
        /// </summary>
        public static string sContains {
            get {
                return ResourceManager.GetString("sContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string sCopy {
            get {
                return ResourceManager.GetString("sCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string sDelete {
            get {
                return ResourceManager.GetString("sDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected.
        /// </summary>
        public static string sDeleteSelected {
            get {
                return ResourceManager.GetString("sDeleteSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string sDetails {
            get {
                return ResourceManager.GetString("sDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display date.
        /// </summary>
        public static string sDisplayDate {
            get {
                return ResourceManager.GetString("sDisplayDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File exists already! Do you want to overwrite it?.
        /// </summary>
        public static string sDoYouWantToReplaceExistedFile {
            get {
                return ResourceManager.GetString("sDoYouWantToReplaceExistedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string sEdit {
            get {
                return ResourceManager.GetString("sEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter.
        /// </summary>
        public static string sEnter {
            get {
                return ResourceManager.GetString("sEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to error.
        /// </summary>
        public static string sError {
            get {
                return ResourceManager.GetString("sError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while add.
        /// </summary>
        public static string sErrorAdd {
            get {
                return ResourceManager.GetString("sErrorAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection error.
        /// </summary>
        public static string sErrorConnection {
            get {
                return ResourceManager.GetString("sErrorConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current request was canceled.
        /// </summary>
        public static string sErrorCurrentRequestWasCanceled {
            get {
                return ResourceManager.GetString("sErrorCurrentRequestWasCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data receive error.
        /// </summary>
        public static string sErrorDataReceive {
            get {
                return ResourceManager.GetString("sErrorDataReceive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data save error.
        /// </summary>
        public static string sErrorDataSave {
            get {
                return ResourceManager.GetString("sErrorDataSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified Date or Time is wrong.
        /// </summary>
        public static string sErrorDateTime {
            get {
                return ResourceManager.GetString("sErrorDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while delete.
        /// </summary>
        public static string sErrorDelete {
            get {
                return ResourceManager.GetString("sErrorDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot open file.
        /// </summary>
        public static string sErrorFile {
            get {
                return ResourceManager.GetString("sErrorFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found.
        /// </summary>
        public static string sErrorFileNotFound {
            get {
                return ResourceManager.GetString("sErrorFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item with such name already exists.
        /// </summary>
        public static string sErrorItemNameExists {
            get {
                return ResourceManager.GetString("sErrorItemNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while items add.
        /// </summary>
        public static string sErrorItemsAdd {
            get {
                return ResourceManager.GetString("sErrorItemsAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file.
        /// </summary>
        public static string sErrorNoFile {
            get {
                return ResourceManager.GetString("sErrorNoFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No item with such ID.
        /// </summary>
        public static string sErrorNoItemWithSuchID {
            get {
                return ResourceManager.GetString("sErrorNoItemWithSuchID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, but you are not allowed {0} {1}. If you believe that this prohibition is wrong, contact your system administrator.
        /// </summary>
        public static string sErrorPermissions {
            get {
                return ResourceManager.GetString("sErrorPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors.
        /// </summary>
        public static string sErrors {
            get {
                return ResourceManager.GetString("sErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while save.
        /// </summary>
        public static string sErrorSave {
            get {
                return ResourceManager.GetString("sErrorSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout. (target action did not happen in {0} seconds).
        /// </summary>
        public static string sErrorTimeout {
            get {
                return ResourceManager.GetString("sErrorTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error.
        /// </summary>
        public static string sErrorUnknown {
            get {
                return ResourceManager.GetString("sErrorUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while update.
        /// </summary>
        public static string sErrorUpdate {
            get {
                return ResourceManager.GetString("sErrorUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some fields have wrong data.
        /// </summary>
        public static string sErrorWrongFields {
            get {
                return ResourceManager.GetString("sErrorWrongFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong ID.
        /// </summary>
        public static string sErrorWrongID {
            get {
                return ResourceManager.GetString("sErrorWrongID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string sExit {
            get {
                return ResourceManager.GetString("sExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string sExport {
            get {
                return ResourceManager.GetString("sExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string sFile {
            get {
                return ResourceManager.GetString("sFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filename.
        /// </summary>
        public static string sFilename {
            get {
                return ResourceManager.GetString("sFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        public static string sFiles {
            get {
                return ResourceManager.GetString("sFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files uploading.
        /// </summary>
        public static string sFilesUploading {
            get {
                return ResourceManager.GetString("sFilesUploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File timings.
        /// </summary>
        public static string sFileTimings {
            get {
                return ResourceManager.GetString("sFileTimings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters.
        /// </summary>
        public static string sFilters {
            get {
                return ResourceManager.GetString("sFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        public static string sFolder {
            get {
                return ResourceManager.GetString("sFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folders.
        /// </summary>
        public static string sFolders {
            get {
                return ResourceManager.GetString("sFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fri.
        /// </summary>
        public static string sFri {
            get {
                return ResourceManager.GetString("sFri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from.
        /// </summary>
        public static string sFrom {
            get {
                return ResourceManager.GetString("sFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide details.
        /// </summary>
        public static string sHideDetails {
            get {
                return ResourceManager.GetString("sHideDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string sImport {
            get {
                return ResourceManager.GetString("sImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In.
        /// </summary>
        public static string sIn {
            get {
                return ResourceManager.GetString("sIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string sInformation {
            get {
                return ResourceManager.GetString("sInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want to delete these items?.
        /// </summary>
        public static string sItemsDeleteConfirmation {
            get {
                return ResourceManager.GetString("sItemsDeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing.
        /// </summary>
        public static string sMissing {
            get {
                return ResourceManager.GetString("sMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing.
        /// </summary>
        public static string sMissing1 {
            get {
                return ResourceManager.GetString("sMissing1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified date.
        /// </summary>
        public static string sModifiedDate {
            get {
                return ResourceManager.GetString("sModifiedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mon.
        /// </summary>
        public static string sMon {
            get {
                return ResourceManager.GetString("sMon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move.
        /// </summary>
        public static string sMove {
            get {
                return ResourceManager.GetString("sMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string sName {
            get {
                return ResourceManager.GetString("sName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string sNext {
            get {
                return ResourceManager.GetString("sNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string sNo {
            get {
                return ResourceManager.GetString("sNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No actions for this item.
        /// </summary>
        public static string sNoActionsForThisItem {
            get {
                return ResourceManager.GetString("sNoActionsForThisItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node is missing.
        /// </summary>
        public static string sNodeIsMissing {
            get {
                return ResourceManager.GetString("sNodeIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No items selected.
        /// </summary>
        public static string sNoItemsSelected {
            get {
                return ResourceManager.GetString("sNoItemsSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No selection.
        /// </summary>
        public static string sNoSelection {
            get {
                return ResourceManager.GetString("sNoSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not applicable.
        /// </summary>
        public static string sNotApplicable {
            get {
                return ResourceManager.GetString("sNotApplicable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string sOk {
            get {
                return ResourceManager.GetString("sOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string sOther {
            get {
                return ResourceManager.GetString("sOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out.
        /// </summary>
        public static string sOut {
            get {
                return ResourceManager.GetString("sOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent.
        /// </summary>
        public static string sParent {
            get {
                return ResourceManager.GetString("sParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string sPassword {
            get {
                return ResourceManager.GetString("sPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string sPath {
            get {
                return ResourceManager.GetString("sPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string sPause {
            get {
                return ResourceManager.GetString("sPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period.
        /// </summary>
        public static string sPeriod {
            get {
                return ResourceManager.GetString("sPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences.
        /// </summary>
        public static string sPreferences {
            get {
                return ResourceManager.GetString("sPreferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press.
        /// </summary>
        public static string sPress {
            get {
                return ResourceManager.GetString("sPress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string sPreview {
            get {
                return ResourceManager.GetString("sPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string sProfile {
            get {
                return ResourceManager.GetString("sProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string sProperties {
            get {
                return ResourceManager.GetString("sProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to qty.
        /// </summary>
        public static string sQty {
            get {
                return ResourceManager.GetString("sQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string sQuantity {
            get {
                return ResourceManager.GetString("sQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string sRefresh {
            get {
                return ResourceManager.GetString("sRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh the list.
        /// </summary>
        public static string sRefreshTheList {
            get {
                return ResourceManager.GetString("sRefreshTheList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration date.
        /// </summary>
        public static string sRegistrationDate {
            get {
                return ResourceManager.GetString("sRegistrationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string sRename {
            get {
                return ResourceManager.GetString("sRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renaming.
        /// </summary>
        public static string sRenaming {
            get {
                return ResourceManager.GetString("sRenaming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sat.
        /// </summary>
        public static string sSat {
            get {
                return ResourceManager.GetString("sSat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string sSave {
            get {
                return ResourceManager.GetString("sSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save all changes.
        /// </summary>
        public static string sSaveAllChanges {
            get {
                return ResourceManager.GetString("sSaveAllChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string sSearch {
            get {
                return ResourceManager.GetString("sSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See the log.
        /// </summary>
        public static string sSeeTheLog {
            get {
                return ResourceManager.GetString("sSeeTheLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string sSelect {
            get {
                return ResourceManager.GetString("sSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string sSelect1 {
            get {
                return ResourceManager.GetString("sSelect1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to selected.
        /// </summary>
        public static string sSelected {
            get {
                return ResourceManager.GetString("sSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select file.
        /// </summary>
        public static string sSelectFile {
            get {
                return ResourceManager.GetString("sSelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select files.
        /// </summary>
        public static string sSelectFiles {
            get {
                return ResourceManager.GetString("sSelectFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string sShow {
            get {
                return ResourceManager.GetString("sShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show all.
        /// </summary>
        public static string sShowAll {
            get {
                return ResourceManager.GetString("sShowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShowDetails.
        /// </summary>
        public static string sShowDetails {
            get {
                return ResourceManager.GetString("sShowDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source number.
        /// </summary>
        public static string sSourceNumber {
            get {
                return ResourceManager.GetString("sSourceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified item is missing.
        /// </summary>
        public static string sSpecifiedItemIsMissing {
            get {
                return ResourceManager.GetString("sSpecifiedItemIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified item is wrong.
        /// </summary>
        public static string sSpecifiedItemIsWrong {
            get {
                return ResourceManager.GetString("sSpecifiedItemIsWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string sStart {
            get {
                return ResourceManager.GetString("sStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start now.
        /// </summary>
        public static string sStartNow {
            get {
                return ResourceManager.GetString("sStartNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string sStatus {
            get {
                return ResourceManager.GetString("sStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string sSubject {
            get {
                return ResourceManager.GetString("sSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUN.
        /// </summary>
        public static string sSun {
            get {
                return ResourceManager.GetString("sSun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string sTags {
            get {
                return ResourceManager.GetString("sTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target number.
        /// </summary>
        public static string sTargetNumber {
            get {
                return ResourceManager.GetString("sTargetNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks.
        /// </summary>
        public static string sTasks {
            get {
                return ResourceManager.GetString("sTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string sText {
            get {
                return ResourceManager.GetString("sText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tomorrow + 1.
        /// </summary>
        public static string sTheDayAfterTomorrow {
            get {
                return ResourceManager.GetString("sTheDayAfterTomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are not any nodes.
        /// </summary>
        public static string sThereAreNotAnyNodes {
            get {
                return ResourceManager.GetString("sThereAreNotAnyNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thu.
        /// </summary>
        public static string sThu {
            get {
                return ResourceManager.GetString("sThu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To add.
        /// </summary>
        public static string sToAdd {
            get {
                return ResourceManager.GetString("sToAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string sToday {
            get {
                return ResourceManager.GetString("sToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To delete.
        /// </summary>
        public static string sToDelete {
            get {
                return ResourceManager.GetString("sToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To modify.
        /// </summary>
        public static string sToModify {
            get {
                return ResourceManager.GetString("sToModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tomorrow.
        /// </summary>
        public static string sTomorrow {
            get {
                return ResourceManager.GetString("sTomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TUE.
        /// </summary>
        public static string sTue {
            get {
                return ResourceManager.GetString("sTue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string sType {
            get {
                return ResourceManager.GetString("sType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string sUnknown {
            get {
                return ResourceManager.GetString("sUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string sUpdate {
            get {
                return ResourceManager.GetString("sUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up to.
        /// </summary>
        public static string sUpto {
            get {
                return ResourceManager.GetString("sUpto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string sUsername {
            get {
                return ResourceManager.GetString("sUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string sValue {
            get {
                return ResourceManager.GetString("sValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string sVersion {
            get {
                return ResourceManager.GetString("sVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to warning.
        /// </summary>
        public static string sWarning {
            get {
                return ResourceManager.GetString("sWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wed.
        /// </summary>
        public static string sWed {
            get {
                return ResourceManager.GetString("sWed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string sWeekLetter1 {
            get {
                return ResourceManager.GetString("sWeekLetter1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W.
        /// </summary>
        public static string sWeekLetter2 {
            get {
                return ResourceManager.GetString("sWeekLetter2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E.
        /// </summary>
        public static string sWeekLetter3 {
            get {
                return ResourceManager.GetString("sWeekLetter3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E.
        /// </summary>
        public static string sWeekLetter4 {
            get {
                return ResourceManager.GetString("sWeekLetter4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to K.
        /// </summary>
        public static string sWeekLetter5 {
            get {
                return ResourceManager.GetString("sWeekLetter5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string sWeekLetter6 {
            get {
                return ResourceManager.GetString("sWeekLetter6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong credentials.
        /// </summary>
        public static string sWrongCredentials {
            get {
                return ResourceManager.GetString("sWrongCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong file name.
        /// </summary>
        public static string sWrongFilename {
            get {
                return ResourceManager.GetString("sWrongFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong item.
        /// </summary>
        public static string sWrongItem {
            get {
                return ResourceManager.GetString("sWrongItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string sYear {
            get {
                return ResourceManager.GetString("sYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string sYes {
            get {
                return ResourceManager.GetString("sYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yesterday.
        /// </summary>
        public static string sYesterday {
            get {
                return ResourceManager.GetString("sYesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to refresh.
        /// </summary>
        public static string sYouHaveToRefresh {
            get {
                return ResourceManager.GetString("sYouHaveToRefresh", resourceCulture);
            }
        }
    }
}
